AWSTemplateFormatVersion "2010-09-09"
Parameters do
  _include 'include/params_keypair.rb'
  _include 'include/params_instancetype_pvm.rb'
end
Mappings do
  _include 'include/map_ami_pvm.rb'
end
Resources do
  _include 'include/single/elb.rb', {instance: "AmimotoSingle"}
  AmimotoSingle do
    Type "AWS::EC2::Instance"
    Properties do
      DisableApiTermination "FALSE"
      ImageId do
        Fn__FindInMap [
          "MPAmimotov4",
          _{
            Ref "AWS::Region"
          },
          "AMI"
        ]
      end
      InstanceType do
        Ref "InstanceType"
      end
      KeyName do
        Ref "KeyName"
      end
      SecurityGroupIds [
        _{
          Ref "sgAMIMOTO11AutogenByAWSMP"
        }
      ]
      Monitoring "false"
      Tags [
        _{
          Key "Name"
          Value "mp-amimoto"
        }
      ]
    end
  end
  sgAMIMOTO11AutogenByAWSMP do
    Type "AWS::EC2::SecurityGroup"
    Properties do
      GroupDescription "This security group was generated by AWS Marketplace and is based on recommended settings for AMIMOTO version 11 provided by DigitalCube Co Ltd"
      SecurityGroupIngress [
        _{
          IpProtocol "tcp"
          FromPort 22
          ToPort 22
          CidrIp "0.0.0.0/0"
        },
        _{
          IpProtocol "tcp"
          FromPort 80
          ToPort 80
          CidrIp "0.0.0.0/0"
        }
      ]
    end
  end
end
Description ""
Outputs do
  WebSiteURL do
    Description "WordPress Site URL (Please wait a few minutes for the upgrade of WordPress to access for the first time.)"
    Value do
      Fn__Join [
        "",
        [
          "http://",
          _{
            Fn__GetAtt "LoadBalancer", "DNSName"
          }
        ]
      ]
    end
  end
end
